/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CadCliDAO;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import javax.swing.JOptionPane;
import vo.CadCliVO;

public class CadCliVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public CadCliVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSexo_Cadastro = new javax.swing.ButtonGroup();
        pnFundo_Cadastro = new javax.swing.JPanel();
        pnTitulo_Cadastro = new javax.swing.JPanel();
        lblTitulo_Cadastro = new javax.swing.JLabel();
        lblNome_Cadastro = new javax.swing.JLabel();
        txtNome_Cadastro = new javax.swing.JTextField();
        lblEndereco_Cadastro = new javax.swing.JLabel();
        txtDataNasc_Cadastro = new javax.swing.JTextField();
        lblDataNasc_Cadastro = new javax.swing.JLabel();
        txtHorario_Cadastro = new javax.swing.JTextField();
        lblEmail_Cadastro = new javax.swing.JLabel();
        txtEndereco_Cadastro = new javax.swing.JTextField();
        lblHorario_Cadastro = new javax.swing.JLabel();
        txtEmail_Cadastro = new javax.swing.JTextField();
        lblTelefone1_Cadastro = new javax.swing.JLabel();
        txtRG_Cadastro = new javax.swing.JTextField();
        lblRG_Cadastro = new javax.swing.JLabel();
        txtTelefone2_Cadastro = new javax.swing.JTextField();
        lblTelefone2_Cadastro = new javax.swing.JLabel();
        txtTelefoneResp_Cadastro = new javax.swing.JTextField();
        txtTelefone1_Cadastro = new javax.swing.JTextField();
        lblCodigo_Cadastro = new javax.swing.JLabel();
        lblTelefoneResp_Cadastro = new javax.swing.JLabel();
        txtCodigo_Cadastro = new javax.swing.JTextField();
        lblResponsavel_Cadastro = new javax.swing.JLabel();
        rbtnFem = new javax.swing.JRadioButton();
        rbtnMasc = new javax.swing.JRadioButton();
        rbtnOutro = new javax.swing.JRadioButton();
        btnCadastrar_Cadastro = new javax.swing.JButton();
        txtResponsavel_Cadastro = new javax.swing.JTextField();
        lblSexo_Cadastro = new javax.swing.JLabel();
        btnConsultar_Cadastro = new javax.swing.JButton();
        lblModalidade_Cadastro = new javax.swing.JLabel();
        txtModalidade_Cadastro = new javax.swing.JTextField();
        lblPeriodo_Cadastro = new javax.swing.JLabel();
        txtPeriodo_Cadastro = new javax.swing.JTextField();
        lblCPF_Cadastro = new javax.swing.JLabel();
        txtCPF_Cadastro = new javax.swing.JTextField();
        btnExcluir_Cadastro = new javax.swing.JButton();
        btnEditar_Cadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnFundo_Cadastro.setBackground(new java.awt.Color(0, 0, 0));

        pnTitulo_Cadastro.setBackground(new java.awt.Color(102, 102, 102));

        lblTitulo_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTitulo_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo_Cadastro.setText("CADASTRO");
        lblTitulo_Cadastro.setToolTipText("");

        javax.swing.GroupLayout pnTitulo_CadastroLayout = new javax.swing.GroupLayout(pnTitulo_Cadastro);
        pnTitulo_Cadastro.setLayout(pnTitulo_CadastroLayout);
        pnTitulo_CadastroLayout.setHorizontalGroup(
            pnTitulo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo_Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTitulo_CadastroLayout.setVerticalGroup(
            pnTitulo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitulo_CadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblNome_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblNome_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblNome_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNome_Cadastro.setText("Nome:");
        lblNome_Cadastro.setToolTipText("");

        txtNome_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtNome_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtNome_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome_CadastroActionPerformed(evt);
            }
        });

        lblEndereco_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblEndereco_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEndereco_Cadastro.setText("Endereço:");
        lblEndereco_Cadastro.setToolTipText("");

        txtDataNasc_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtDataNasc_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtDataNasc_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNasc_CadastroActionPerformed(evt);
            }
        });

        lblDataNasc_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblDataNasc_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblDataNasc_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataNasc_Cadastro.setText("Data de nascimento:");
        lblDataNasc_Cadastro.setToolTipText("");

        txtHorario_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtHorario_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtHorario_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorario_CadastroActionPerformed(evt);
            }
        });

        lblEmail_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblEmail_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmail_Cadastro.setText("Email:");
        lblEmail_Cadastro.setToolTipText("");

        txtEndereco_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtEndereco_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtEndereco_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndereco_CadastroActionPerformed(evt);
            }
        });

        lblHorario_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblHorario_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblHorario_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHorario_Cadastro.setText("Horário:");
        lblHorario_Cadastro.setToolTipText("");

        txtEmail_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail_CadastroActionPerformed(evt);
            }
        });

        lblTelefone1_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTelefone1_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone1_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelefone1_Cadastro.setText("Telefone 1:");
        lblTelefone1_Cadastro.setToolTipText("");

        txtRG_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtRG_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtRG_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRG_CadastroActionPerformed(evt);
            }
        });

        lblRG_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblRG_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblRG_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRG_Cadastro.setText("RG:");
        lblRG_Cadastro.setToolTipText("");

        txtTelefone2_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefone2_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefone2_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone2_CadastroActionPerformed(evt);
            }
        });

        lblTelefone2_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTelefone2_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone2_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelefone2_Cadastro.setText("Telefone 2:");
        lblTelefone2_Cadastro.setToolTipText("");

        txtTelefoneResp_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefoneResp_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefoneResp_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneResp_CadastroActionPerformed(evt);
            }
        });

        txtTelefone1_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefone1_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefone1_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone1_CadastroActionPerformed(evt);
            }
        });

        lblCodigo_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblCodigo_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo_Cadastro.setText("Código:");
        lblCodigo_Cadastro.setToolTipText("");

        lblTelefoneResp_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTelefoneResp_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefoneResp_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelefoneResp_Cadastro.setText("Telefone do responsável:");
        lblTelefoneResp_Cadastro.setToolTipText("");

        txtCodigo_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigo_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigo_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo_CadastroActionPerformed(evt);
            }
        });

        lblResponsavel_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblResponsavel_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblResponsavel_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResponsavel_Cadastro.setText("Responsável:");
        lblResponsavel_Cadastro.setToolTipText("");

        rbtnFem.setBackground(new java.awt.Color(0, 0, 0));
        btngSexo_Cadastro.add(rbtnFem);
        rbtnFem.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        rbtnFem.setForeground(new java.awt.Color(255, 255, 255));
        rbtnFem.setText("feminino");
        rbtnFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemActionPerformed(evt);
            }
        });

        rbtnMasc.setBackground(new java.awt.Color(0, 0, 0));
        btngSexo_Cadastro.add(rbtnMasc);
        rbtnMasc.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        rbtnMasc.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMasc.setText("masculino");
        rbtnMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMascActionPerformed(evt);
            }
        });

        rbtnOutro.setBackground(new java.awt.Color(0, 0, 0));
        btngSexo_Cadastro.add(rbtnOutro);
        rbtnOutro.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        rbtnOutro.setForeground(new java.awt.Color(255, 255, 255));
        rbtnOutro.setText("outro");
        rbtnOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOutroActionPerformed(evt);
            }
        });

        btnCadastrar_Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        btnCadastrar_Cadastro.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrar_Cadastro.setText("Cadastrar");
        btnCadastrar_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar_CadastroActionPerformed(evt);
            }
        });

        txtResponsavel_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtResponsavel_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtResponsavel_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponsavel_CadastroActionPerformed(evt);
            }
        });

        lblSexo_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblSexo_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblSexo_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSexo_Cadastro.setText("Sexo do aluno:");
        lblSexo_Cadastro.setToolTipText("");

        btnConsultar_Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        btnConsultar_Cadastro.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar_Cadastro.setText("Consultar");
        btnConsultar_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar_CadastroActionPerformed(evt);
            }
        });

        lblModalidade_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblModalidade_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblModalidade_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModalidade_Cadastro.setText("Modalidade:");
        lblModalidade_Cadastro.setToolTipText("");

        txtModalidade_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtModalidade_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtModalidade_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidade_CadastroActionPerformed(evt);
            }
        });

        lblPeriodo_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblPeriodo_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodo_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPeriodo_Cadastro.setText("Período:");
        lblPeriodo_Cadastro.setToolTipText("");

        txtPeriodo_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtPeriodo_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtPeriodo_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeriodo_CadastroActionPerformed(evt);
            }
        });

        lblCPF_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblCPF_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCPF_Cadastro.setText("CPF:");
        lblCPF_Cadastro.setToolTipText("");

        txtCPF_Cadastro.setBackground(new java.awt.Color(204, 204, 204));
        txtCPF_Cadastro.setForeground(new java.awt.Color(51, 51, 51));
        txtCPF_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPF_CadastroActionPerformed(evt);
            }
        });

        btnExcluir_Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        btnExcluir_Cadastro.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir_Cadastro.setText("Excluir");
        btnExcluir_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir_CadastroActionPerformed(evt);
            }
        });

        btnEditar_Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar_Cadastro.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        btnEditar_Cadastro.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar_Cadastro.setText("Editar");
        btnEditar_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar_CadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFundo_CadastroLayout = new javax.swing.GroupLayout(pnFundo_Cadastro);
        pnFundo_Cadastro.setLayout(pnFundo_CadastroLayout);
        pnFundo_CadastroLayout.setHorizontalGroup(
            pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitulo_Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                        .addComponent(txtTelefone1_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                                .addComponent(rbtnMasc)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnFem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnOutro))
                            .addComponent(lblSexo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                                .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmail_Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNome_Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNome_Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail_Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblRG_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRG_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefone1_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblResponsavel_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtResponsavel_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTelefone2_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelefone2_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addComponent(lblCodigo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCodigo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnFundo_CadastroLayout.createSequentialGroup()
                                            .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTelefoneResp_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblTelefoneResp_Cadastro))
                                            .addGap(37, 37, 37)
                                            .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                                                    .addComponent(btnCadastrar_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnEditar_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                                                    .addComponent(btnConsultar_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnExcluir_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnFundo_CadastroLayout.createSequentialGroup()
                                            .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblEndereco_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtEndereco_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblDataNasc_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDataNasc_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtCPF_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblCPF_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(60, 60, 60)
                                            .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPeriodo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblPeriodo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblModalidade_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtModalidade_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblHorario_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtHorario_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 116, Short.MAX_VALUE))))
        );
        pnFundo_CadastroLayout.setVerticalGroup(
            pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                .addComponent(pnTitulo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                        .addComponent(lblNome_Cadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail_Cadastro)
                            .addComponent(lblDataNasc_Cadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataNasc_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorario_Cadastro)
                            .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblRG_Cadastro)
                                .addComponent(lblCPF_Cadastro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHorario_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRG_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPF_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefone2_Cadastro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelefone1_Cadastro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefone1_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefone2_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblTelefoneResp_Cadastro)
                                            .addComponent(lblResponsavel_Cadastro))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTelefoneResp_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtResponsavel_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)
                                        .addComponent(lblSexo_Cadastro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rbtnMasc)
                                            .addComponent(rbtnFem)
                                            .addComponent(rbtnOutro)))
                                    .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConsultar_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnCadastrar_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEditar_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCodigo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnFundo_CadastroLayout.createSequentialGroup()
                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEndereco_Cadastro)
                            .addComponent(lblModalidade_Cadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnFundo_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndereco_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModalidade_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPeriodo_Cadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPeriodo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundo_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundo_Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNome_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome_CadastroActionPerformed

    private void txtDataNasc_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNasc_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNasc_CadastroActionPerformed

    private void txtHorario_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorario_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorario_CadastroActionPerformed

    private void txtEndereco_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndereco_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndereco_CadastroActionPerformed

    private void txtEmail_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_CadastroActionPerformed

    private void txtRG_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRG_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRG_CadastroActionPerformed

    private void txtTelefone2_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone2_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefone2_CadastroActionPerformed

    private void txtTelefoneResp_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneResp_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneResp_CadastroActionPerformed

    private void txtTelefone1_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone1_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefone1_CadastroActionPerformed

    private void txtCodigo_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo_CadastroActionPerformed

    private void rbtnFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemActionPerformed

    private void rbtnMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMascActionPerformed

    private void rbtnOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOutroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnOutroActionPerformed

    private void btnCadastrar_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar_CadastroActionPerformed
        CadCliDAO dao = new CadCliDAO();
        CadCliVO vo = new CadCliVO();
        
        if (!txtNome_Cadastro.getText().equals("")){
            
            
            vo.setCodigo(txtCodigo_Cadastro.getText());
            vo.setNome(txtNome_Cadastro.getText().toUpperCase());
            vo.setEndereco(txtEndereco_Cadastro.getText().toUpperCase());
            vo.setEmail(txtEmail_Cadastro.getText().toUpperCase());
            vo.setDtnasc(txtDataNasc_Cadastro.getText());
            vo.setRg(txtRG_Cadastro.getText().replaceAll("\\D+",""));
            vo.setCpf(txtCPF_Cadastro.getText().replaceAll("\\D+",""));
            vo.setTelefone1(txtTelefone1_Cadastro.getText().replaceAll("\\D+",""));
            vo.setTelefone2(txtTelefone2_Cadastro.getText().replaceAll("\\D+",""));
            vo.setResponsavel(txtResponsavel_Cadastro.getText().toUpperCase());
            vo.setTelefoneResp(txtTelefoneResp_Cadastro.getText().replaceAll("\\D+",""));
            vo.setModalidade(txtModalidade_Cadastro.getText());
            vo.setPeriodo(txtPeriodo_Cadastro.getText());
            vo.setHorario(txtHorario_Cadastro.getText());

            if (rbtnMasc.isSelected()) {
                vo.setSexo(rbtnMasc.getText());
            } else if (rbtnFem.isSelected()) {
                vo.setSexo(rbtnFem.getText());
            } else if (rbtnOutro.isSelected()) {
                vo.setSexo(rbtnOutro.getText());
            }
            
            
            dao.incluirClientes(vo);
            
            txtCodigo_Cadastro.setText("");
            txtNome_Cadastro.setText("");
            txtEndereco_Cadastro.setText("");
            txtEmail_Cadastro.setText("");
            txtDataNasc_Cadastro.setText("");
            txtRG_Cadastro.setText("");
            txtCPF_Cadastro.setText("");
            txtTelefone1_Cadastro.setText("");
            txtTelefone2_Cadastro.setText("");
            txtResponsavel_Cadastro.setText("");
            txtTelefoneResp_Cadastro.setText("");
            txtModalidade_Cadastro.setText("");
            txtPeriodo_Cadastro.setText("");
            txtHorario_Cadastro.setText("");
            btngSexo_Cadastro.clearSelection();


            
            
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
        }else{
            if(txtNome_Cadastro.getText().equals("")){
                JOptionPane.showMessageDialog(null, "CAMO NOME NÃO FOI PREENCHIDO!");
            }
        }
    }//GEN-LAST:event_btnCadastrar_CadastroActionPerformed

    private void txtResponsavel_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsavel_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsavel_CadastroActionPerformed

    private void btnConsultar_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar_CadastroActionPerformed
        txtCodigo_Cadastro.setEditable(true);
        txtNome_Cadastro.setEditable(true);
        txtEndereco_Cadastro.setEditable(true);
        txtRG_Cadastro.setEditable(true);
        txtCPF_Cadastro.setEditable(true);
        txtDataNasc_Cadastro.setEditable(true);
        txtTelefone1_Cadastro.setEditable(true);
        txtTelefone2_Cadastro.setEditable(true);
        txtEmail_Cadastro.setEditable(true);
        txtResponsavel_Cadastro.setEditable(true);
        txtTelefoneResp_Cadastro.setEditable(true);
        txtModalidade_Cadastro.setEditable(true);
        txtPeriodo_Cadastro.setEditable(true);
        txtHorario_Cadastro.setEditable(true);

        
        String com=txtCodigo_Cadastro.getText();
        CadCliDAO dao=new CadCliDAO();
        CadCliVO vo=new CadCliVO();
        Collection list = new ArrayList<CadCliVO>();
        list = dao.selectCadCli("codigo",com);
        Iterator i = list.iterator();
        if (list.isEmpty()){
            JOptionPane.showMessageDialog(null,"Não existe cliente cadastrado com este código.");
            txtCodigo_Cadastro.setText("");
        }
        while(i.hasNext()){
            Object elemento = i.next();
            CadCliVO palavra=(CadCliVO)elemento;
            txtNome_Cadastro.setText(palavra.getNome());
            txtEndereco_Cadastro.setText(palavra.getEndereco());
            txtRG_Cadastro.setText(palavra.getRg());
            txtCPF_Cadastro.setText(palavra.getCpf());
            txtDataNasc_Cadastro.setText(palavra.getDtnasc());
            txtTelefone1_Cadastro.setText(palavra.getTelefone1());
            txtTelefone2_Cadastro.setText(palavra.getTelefone2());
            txtEmail_Cadastro.setText(palavra.getEmail());
            txtResponsavel_Cadastro.setText(palavra.getResponsavel());
            txtTelefoneResp_Cadastro.setText(palavra.getTelefoneResp());
            txtModalidade_Cadastro.setText(palavra.getModalidade());
            txtPeriodo_Cadastro.setText(palavra.getPeriodo());
            txtHorario_Cadastro.setText(palavra.getHorario());


            txtCodigo_Cadastro.setEditable(false);
            btnCadastrar_Cadastro.setEnabled(false);
            btnEditar_Cadastro.setEnabled(false);
            btnExcluir_Cadastro.setEnabled(false);
            btnConsultar_Cadastro.setEnabled(false);

        }
        
    }//GEN-LAST:event_btnConsultar_CadastroActionPerformed

    private void txtModalidade_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidade_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidade_CadastroActionPerformed

    private void txtPeriodo_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeriodo_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeriodo_CadastroActionPerformed

    private void txtCPF_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPF_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPF_CadastroActionPerformed

    private void btnExcluir_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir_CadastroActionPerformed
        btnCadastrar_Cadastro.setEnabled(true);
        btnEditar_Cadastro.setEnabled(true);
        btnExcluir_Cadastro.setEnabled(true);
        btnConsultar_Cadastro.setEnabled(true);
        CadCliDAO dao = new CadCliDAO();
        CadCliVO vo = new CadCliVO();
        vo.setCodigo(txtCodigo_Cadastro.getText());
        vo.setNome(txtNome_Cadastro.getText().toUpperCase());
        vo.setEndereco(txtEndereco_Cadastro.getText().toUpperCase());
        vo.setRg(txtRG_Cadastro.getText());
        vo.setCpf(txtCPF_Cadastro.getText());
        vo.setDtnasc(txtDataNasc_Cadastro.getText());
        vo.setTelefone1(txtTelefone1_Cadastro.getText());
        vo.setTelefone2(txtTelefone2_Cadastro.getText());
        vo.setEmail(txtEmail_Cadastro.getText().toUpperCase());
        vo.setResponsavel(txtResponsavel_Cadastro.getText());
        vo.setTelefoneResp(txtTelefoneResp_Cadastro.getText().toUpperCase());
        vo.setModalidade(txtModalidade_Cadastro.getText());
        vo.setPeriodo(txtPeriodo_Cadastro.getText());
        vo.setHorario(txtHorario_Cadastro.getText());

        dao.deleteCliente(vo);

        txtCodigo_Cadastro.setText("");
        txtNome_Cadastro.setText("");
        txtEndereco_Cadastro.setText("");
        txtRG_Cadastro.setText("");
        txtCPF_Cadastro.setText("");
        txtDataNasc_Cadastro.setText("");
        txtTelefone1_Cadastro.setText("");
        txtTelefone2_Cadastro.setText("");
        txtEmail_Cadastro.setText("");
        txtResponsavel_Cadastro.setText("");
        txtTelefoneResp_Cadastro.setText("");
        txtModalidade_Cadastro.setText("");
        txtPeriodo_Cadastro.setText("");
        txtHorario_Cadastro.setText("");

        JOptionPane.showMessageDialog(null,"Cliente Excluido");
    }//GEN-LAST:event_btnExcluir_CadastroActionPerformed

    private void btnEditar_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar_CadastroActionPerformed
        btnCadastrar_Cadastro.setEnabled(true);
        btnEditar_Cadastro.setEnabled(true);
        btnExcluir_Cadastro.setEnabled(true);
        btnConsultar_Cadastro.setEnabled(true);
        
        CadCliDAO dao = new CadCliDAO();
        CadCliVO vo = new CadCliVO();
        if ((!txtNome_Cadastro.getText().equals(""))&(!txtEndereco_Cadastro.getText().equals(""))&(!txtRG_Cadastro.getText().equals(""))&
            (!txtCPF_Cadastro.getText().equals(""))&(!txtDataNasc_Cadastro.getText().equals(""))&(!txtTelefone1_Cadastro.getText().equals(""))&
            (!txtTelefone2_Cadastro.getText().equals(""))&(!txtEmail_Cadastro.getText().equals(""))&(!txtResponsavel_Cadastro.getText().equals(""))&
            (!txtTelefoneResp_Cadastro.getText().equals(""))&(!txtModalidade_Cadastro.getText().equals(""))&(!txtPeriodo_Cadastro.getText().equals(""))&
            (!txtHorario_Cadastro.getText().equals("")))
        {
            vo.setCodigo(txtCodigo_Cadastro.getText());
            vo.setNome(txtNome_Cadastro.getText().toUpperCase());
            vo.setEndereco(txtEndereco_Cadastro.getText().toUpperCase());
            vo.setRg(txtRG_Cadastro.getText().replaceAll("\\D+",""));
            vo.setCpf(txtCPF_Cadastro.getText().replaceAll("\\D+",""));
            vo.setDtnasc(txtDataNasc_Cadastro.getText());
            vo.setTelefone1(txtTelefone1_Cadastro.getText().replaceAll("\\D+",""));
            vo.setTelefone2(txtTelefone2_Cadastro.getText().replaceAll("\\D+",""));
            vo.setEmail(txtEmail_Cadastro.getText().toUpperCase());
            vo.setResponsavel(txtResponsavel_Cadastro.getText().toUpperCase());
            vo.setTelefoneResp(txtTelefoneResp_Cadastro.getText().replaceAll("\\D+",""));
            vo.setModalidade(txtModalidade_Cadastro.getText());
            vo.setPeriodo(txtPeriodo_Cadastro.getText());
            vo.setHorario(txtHorario_Cadastro.getText());
            dao.atualizaCliente(vo);
            txtNome_Cadastro.setText("");
            txtEndereco_Cadastro.setText("");
            txtRG_Cadastro.setText("");
            txtCPF_Cadastro.setText("");
            txtDataNasc_Cadastro.setText("");
            txtTelefone1_Cadastro.setText("");
            txtTelefone2_Cadastro.setText("");
            txtEmail_Cadastro.setText("");
            txtResponsavel_Cadastro.setText("");
            txtTelefoneResp_Cadastro.setText("");
            txtModalidade_Cadastro.setText("");
            txtPeriodo_Cadastro.setText("");
            txtHorario_Cadastro.setText("");
            JOptionPane.showMessageDialog(null,"CLIENTE ATUALIZADO");
        }
        else if(txtNome_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO NOME NÃO FOI PREENCHIDO");
        }
        else if(txtEndereco_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO ENDEREÇO NÃO FOI PREENCHIDO");
        }
        else if(txtRG_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO RG NÃO FOI PREENCHIDO");
        }
        else if(txtCPF_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO CPF NÃO FOI PREENCHIDO");
        }
        else if(txtDataNasc_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO DATA DE NASCIMENTO NÃO FOI PREENCHIDO");
        }
        else if(txtTelefone1_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO TELEFONE 1 NÃO FOI PREENCHIDO");
        }
        else if(txtTelefone2_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO TELEFONE 2 NÃO FOI PREENCHIDO");
        }
        else if(txtEmail_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO E-MAIL NÃO FOI PREENCHIDO");
        }
        else if(txtResponsavel_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO RESPONSÁVEL NÃO FOI PREENCHIDO");
        }
        else if(txtTelefoneResp_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO TELEFONE DO RESPONSÁVEL NÃO FOI PREENCHIDO");
        }
        else if(txtModalidade_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO MODALIDADE NÃO FOI PREENCHIDO");
        }
        else if(txtPeriodo_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO PERÍODO NÃO FOI PREENCHIDO");
        }
        else if(txtHorario_Cadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPO HORÁRIO NÃO FOI PREENCHIDO");
        }
        else{
            JOptionPane.showMessageDialog(null,"DIVERSOS CAMPOS NÃO FORAM PREENCHIDOS");
        }


    }//GEN-LAST:event_btnEditar_CadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCliVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCliVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCliVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCliVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar_Cadastro;
    private javax.swing.JButton btnConsultar_Cadastro;
    private javax.swing.JButton btnEditar_Cadastro;
    private javax.swing.JButton btnExcluir_Cadastro;
    private javax.swing.ButtonGroup btngSexo_Cadastro;
    private javax.swing.JLabel lblCPF_Cadastro;
    private javax.swing.JLabel lblCodigo_Cadastro;
    private javax.swing.JLabel lblDataNasc_Cadastro;
    private javax.swing.JLabel lblEmail_Cadastro;
    private javax.swing.JLabel lblEndereco_Cadastro;
    private javax.swing.JLabel lblHorario_Cadastro;
    private javax.swing.JLabel lblModalidade_Cadastro;
    private javax.swing.JLabel lblNome_Cadastro;
    private javax.swing.JLabel lblPeriodo_Cadastro;
    private javax.swing.JLabel lblRG_Cadastro;
    private javax.swing.JLabel lblResponsavel_Cadastro;
    private javax.swing.JLabel lblSexo_Cadastro;
    private javax.swing.JLabel lblTelefone1_Cadastro;
    private javax.swing.JLabel lblTelefone2_Cadastro;
    private javax.swing.JLabel lblTelefoneResp_Cadastro;
    private javax.swing.JLabel lblTitulo_Cadastro;
    private javax.swing.JPanel pnFundo_Cadastro;
    private javax.swing.JPanel pnTitulo_Cadastro;
    private javax.swing.JRadioButton rbtnFem;
    private javax.swing.JRadioButton rbtnMasc;
    private javax.swing.JRadioButton rbtnOutro;
    private javax.swing.JTextField txtCPF_Cadastro;
    private javax.swing.JTextField txtCodigo_Cadastro;
    private javax.swing.JTextField txtDataNasc_Cadastro;
    private javax.swing.JTextField txtEmail_Cadastro;
    private javax.swing.JTextField txtEndereco_Cadastro;
    private javax.swing.JTextField txtHorario_Cadastro;
    private javax.swing.JTextField txtModalidade_Cadastro;
    private javax.swing.JTextField txtNome_Cadastro;
    private javax.swing.JTextField txtPeriodo_Cadastro;
    private javax.swing.JTextField txtRG_Cadastro;
    private javax.swing.JTextField txtResponsavel_Cadastro;
    private javax.swing.JTextField txtTelefone1_Cadastro;
    private javax.swing.JTextField txtTelefone2_Cadastro;
    private javax.swing.JTextField txtTelefoneResp_Cadastro;
    // End of variables declaration//GEN-END:variables
}
