/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package monstrinho;

import javax.swing.JOptionPane;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastro_Menu1 = new javax.swing.JButton();
        pnFundo_Menu = new javax.swing.JPanel();
        pnTitulo_Menu = new javax.swing.JPanel();
        lblTitulo_Menu = new javax.swing.JLabel();
        btnCadastro_Menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSobre_Menu = new javax.swing.JButton();

        btnCadastro_Menu1.setBackground(new java.awt.Color(102, 102, 102));
        btnCadastro_Menu1.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro_Menu1.setText("Cadastrar aluno");
        btnCadastro_Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastro_Menu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnFundo_Menu.setBackground(new java.awt.Color(0, 0, 0));

        pnTitulo_Menu.setBackground(new java.awt.Color(102, 102, 102));

        lblTitulo_Menu.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTitulo_Menu.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo_Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo_Menu.setText("MONSTRINHO");
        lblTitulo_Menu.setToolTipText("");

        javax.swing.GroupLayout pnTitulo_MenuLayout = new javax.swing.GroupLayout(pnTitulo_Menu);
        pnTitulo_Menu.setLayout(pnTitulo_MenuLayout);
        pnTitulo_MenuLayout.setHorizontalGroup(
            pnTitulo_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo_Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        pnTitulo_MenuLayout.setVerticalGroup(
            pnTitulo_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitulo_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCadastro_Menu.setBackground(new java.awt.Color(102, 102, 102));
        btnCadastro_Menu.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro_Menu.setText("Cadastrar aluno");
        btnCadastro_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastro_MenuActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monstrinho/monstrobolso.jpg"))); // NOI18N

        btnSobre_Menu.setBackground(new java.awt.Color(102, 102, 102));
        btnSobre_Menu.setForeground(new java.awt.Color(255, 255, 255));
        btnSobre_Menu.setText("Sobre o projeto");
        btnSobre_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobre_MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFundo_MenuLayout = new javax.swing.GroupLayout(pnFundo_Menu);
        pnFundo_Menu.setLayout(pnFundo_MenuLayout);
        pnFundo_MenuLayout.setHorizontalGroup(
            pnFundo_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitulo_Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundo_MenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnFundo_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastro_Menu)
                    .addComponent(btnSobre_Menu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );
        pnFundo_MenuLayout.setVerticalGroup(
            pnFundo_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFundo_MenuLayout.createSequentialGroup()
                .addComponent(pnTitulo_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(pnFundo_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(pnFundo_MenuLayout.createSequentialGroup()
                        .addComponent(btnCadastro_Menu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSobre_Menu)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundo_Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundo_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastro_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastro_MenuActionPerformed
        Cadastro frame = new Cadastro();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastro_MenuActionPerformed

    private void btnCadastro_Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastro_Menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastro_Menu1ActionPerformed

    private void btnSobre_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobre_MenuActionPerformed
         JOptionPane.showMessageDialog(null, "Projeto para criação de um sistema de cadastro de alunos ao Monstrinho Ourinhos.\nFeito por:\nAndrey Nunes Paura\nArthur Souza Queiroz");
    }//GEN-LAST:event_btnSobre_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro_Menu;
    private javax.swing.JButton btnCadastro_Menu1;
    private javax.swing.JButton btnSobre_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitulo_Cadastro;
    private javax.swing.JLabel lblTitulo_Cadastro1;
    private javax.swing.JLabel lblTitulo_Cadastro2;
    private javax.swing.JLabel lblTitulo_Cadastro3;
    private javax.swing.JLabel lblTitulo_Cadastro4;
    private javax.swing.JLabel lblTitulo_Cadastro5;
    private javax.swing.JLabel lblTitulo_Menu;
    private javax.swing.JPanel pnFundo_Menu;
    private javax.swing.JPanel pnTitulo_Cadastro;
    private javax.swing.JPanel pnTitulo_Cadastro1;
    private javax.swing.JPanel pnTitulo_Cadastro2;
    private javax.swing.JPanel pnTitulo_Cadastro3;
    private javax.swing.JPanel pnTitulo_Cadastro4;
    private javax.swing.JPanel pnTitulo_Cadastro5;
    private javax.swing.JPanel pnTitulo_Menu;
    // End of variables declaration//GEN-END:variables
}
